name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          set -xeou pipefail

          mkdir _site
          cd _site
          nix run
      - uses: actions/upload-pages-artifact@v4
  deploy:
    needs: generate
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/upload-pages-artifact@v4
        id: deployment
        with:
          path: result.ics
